pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'Spongepowered (Mixin)'
			url = 'https://repo.spongepowered.org/repository/maven-public/'
		}
		maven {
			name = 'ModPublisher https://github.com/firstdarkdev/modpublisher'
			url "https://maven.firstdark.dev/releases"
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = "${mod_id}"

if(file("${rootDir}/api").exists()) {//Check if API folder exists, if it does, include it
	include 'api'
}
include 'common'
include 'fabric'

// If this repo exists then we pull out changelogs and versions from here - allows for centralized repo for them. Yes, I'm lazy
if (file("../AllChangelogs").exists()) {
	includeBuild("../AllChangelogs")
}