plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    maven {
        name = 'Gradle Plugin Portal'
        url "https://plugins.gradle.org/m2/"
    }

    maven {
        name = 'ModPublisher https://github.com/firstdarkdev/modpublisher'
        url "https://maven.firstdark.dev/releases"
    }
}

dependencies {
    implementation "com.hypherionmc.modutils:modpublisher:2.1.6"
    implementation "com.gradleup.shadow:shadow-gradle-plugin:8.3.6"
}